version: '3'

services:
  modifierr:
    build: .
    ports:
      - "5252:5252"
    environment:
      - WEBSERVER_LISTEN_ADDR=${WEBSERVER_LISTEN_ADDR}
      - SONARR_BASEURL=${SONARR_BASEURL}
      - SONARR_APIKEY=${SONARR_APIKEY}
      - RADARR_BASEURL=${RADARR_BASEURL}
      - RADARR_APIKEY=${RADARR_APIKEY}
      - OVERSEERR_BASEURL=${OVERSEERR_BASEURL}
      - OVERSEERR_APIKEY=${OVERSEERR_APIKEY}
      # Add other environment variables as needed
    volumes:
      - ./app:/app  # Mount your app directory

networks:
  default:
    external:
      name: bridge
